ALTER TABLE cases ADD COLUMN IF NOT EXISTS priority TEXT NOT NULL DEFAULT 'normal';
ALTER TABLE cases ADD COLUMN IF NOT EXISTS escalation_reason TEXT;
ALTER TABLE cases ADD COLUMN IF NOT EXISTS escalated_at TIMESTAMPTZ;